services:
  frontend:
    build: 
      context: ./app/frontend
      dockerfile: Dockerfile  
    volumes:
      - ./app/frontend:/app/frontend
      - /app/frontend/node_modules
    env_file:
      - .env
    ports:
      - "5173:5173"
    entrypoint: ["pnpm", "dev"]
    tty: true
  backend:
    build: 
      context: ./app/backend
      dockerfile: Dockerfile  
    volumes:
      - ./app/backend/cache:/app/backend/cache
    env_file:
      - .env
    ports:
      - "5000:5000"
      - "5001:5001"
    entrypoint: ["python", "src/main.py"]
    develop:
      watch:
        - action: sync+restart
          path: ./app/backend
          target: /app/backend
          ignore:
            - .git
            - '**/node_modules'
            - '**/__pycache__'
            - '**/cache'
    tty: true
    shm_size: 2G
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]