services:
  frontend:
    build: 
      context: ./app/frontend
      dockerfile: Dockerfile  
    volumes:
      - ./app/frontend:/app/frontend
      - /app/frontend/node_modules
    env_file:
      - .env
    ports:
      - "5173:5173"
    entrypoint: ["pnpm", "dev"]
    tty: true
  backend:
    build: 
      context: ./app/backend
      dockerfile: Dockerfile  
    volumes:
      - ./app/backend:/app/backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    entrypoint: ["uvicorn", "--app-dir", "src", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    tty: true
    shm_size: 2G
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  